#if !canImport(ObjectiveC)
import XCTest

extension OpusTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OpusTests = [
        ("testHead", testHead),
        ("testPicture", testPicture),
        ("testTags", testTags),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OpusTests.__allTests__OpusTests),
    ]
}
#endif
